Write a program to implement the naïve Bayesian classifier for a sample training data set stored as a.CSV file. 
Compute the accuracy of the classifier, considering few test data sets.

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,precision_score,recall_score

In [8]:
from sklearn.preprocessing import StandardScaler

In [2]:
df=pd.read_csv("./datasets/diabetes.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [9]:
X=df.drop('Outcome',axis=1)
Y=df['Outcome']

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)

In [11]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
model=GaussianNB()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

In [13]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

print("Predicted:", y_pred.tolist())
print("Actual:   ", y_test.tolist())

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)

Predicted: [1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1]
Actual:    [0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1]
Accuracy : 0.7597402597402597
Precision: 0.607142857

In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [15]:
df = pd.read_csv("./datasets/emails.csv")
df.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5728 entries, 0 to 5727
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   text    5728 non-null   object
 1   spam    5728 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 89.6+ KB


In [16]:
X = df["text"].astype(str)
y = df['spam']

In [17]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [18]:
from sklearn.feature_extraction.text import CountVectorizer 

In [ ]:
vectorizer=CountVectorizer(stop_words="english",ngram_range=(1,2),max_features=20)

In [38]:
x_train_vec=vectorizer.fit_transform(X_train)
x_test_vec=vectorizer.transform(X_test)

In [42]:
feature_name=vectorizer.get_feature_names_out()
print(feature_name)
print(feature_name[1:10])
print(feature_name.shape)
print("\nDocument-Term Matrix:")
print(x_train_vec.toarray())

['10' '2000' '2001' 'cc' 'com' 'ect' 'ect ect' 'enron' 'group' 'hou'
 'hou ect' 'kaminski' 'know' 'pm' 'research' 'subject' 'thanks' 'time'
 'vince' 'vince kaminski']
['2000' '2001' 'cc' 'com' 'ect' 'ect ect' 'enron' 'group' 'hou']
(20,)

Document-Term Matrix:
[[0 2 0 ... 0 4 2]
 [0 0 3 ... 0 4 3]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 0]]


In [44]:
print("x_train_vec shape:", x_train_vec.shape)
print("x_test_vec shape :", x_test_vec.shape)

x_train_vec shape: (4582, 20)
x_test_vec shape : (1146, 20)


In [45]:
model = MultinomialNB()
model.fit(x_train_vec, y_train)
y_pred = model.predict(x_test_vec)

In [51]:
spam_prob=model.feature_log_prob_[1]
nonspam_prob=model.feature_log_prob_[0]
top_indices_spam = spam_prob.argsort()[-15:]
top_indices_nonspam = nonspam_prob.argsort()[-15:]

print("Most Important Spam Words  |  No Spam Words:")
for i, j in zip(reversed(top_indices_spam), reversed(top_indices_nonspam)):
    print(feature_name[i], "    |     ", feature_name[j])

Most Important Spam Words  |  No Spam Words:
subject     |      enron
com     |      ect
time     |      subject
10     |      vince
know     |      hou
group     |      hou ect
research     |      2000
thanks     |      ect ect
2000     |      kaminski
pm     |      com
2001     |      vince kaminski
hou     |      cc
cc     |      pm
vince     |      2001
ect     |      research


In [53]:
acc = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred)
rec = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("\nAccuracy :", acc)
print("Precision:", prec)
print("Recall   :", rec)
print("F1 Score :", f1)


Accuracy : 0.9075043630017452
Precision: 0.7383419689119171
Recall   : 0.9827586206896551
F1 Score : 0.8431952662721893


In [54]:
#  TfidfVectorizer Counts words but also measures how important each word is
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

df = pd.read_csv("./datasets/emails.csv")

X = df["text"].astype(str)
y = df["spam"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# -------- TF-IDF Vectorization --------
vectorizer = TfidfVectorizer(stop_words="english", ngram_range=(1,2), max_features=20)

x_train_vec = vectorizer.fit_transform(X_train)
x_test_vec = vectorizer.transform(X_test)

feature_name = vectorizer.get_feature_names_out()

print(feature_name)
print("x_train_vec shape:", x_train_vec.shape)
print("x_test_vec shape :", x_test_vec.shape)

# -------- Train Naïve Bayes --------
model = MultinomialNB()
model.fit(x_train_vec, y_train)

# -------- Predict --------
y_pred = model.predict(x_test_vec)

# -------- Accuracy Metrics --------
acc = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred)
rec = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("\nAccuracy :", acc)
print("Precision:", prec)
print("Recall   :", rec)
print("F1 Score :", f1)

# -------- Find Important Words --------
spam_prob = model.feature_log_prob_[1]
nonspam_prob = model.feature_log_prob_[0]

top_indices_spam = spam_prob.argsort()[-15:]
top_indices_nonspam = nonspam_prob.argsort()[-15:]

print("\nMost Important Spam Words  |  No Spam Words:")
for i, j in zip(reversed(top_indices_spam), reversed(top_indices_nonspam)):
    print(feature_name[i], "    |     ", feature_name[j])



['10' '2000' '2001' 'cc' 'com' 'ect' 'ect ect' 'enron' 'group' 'hou'
 'hou ect' 'kaminski' 'know' 'pm' 'research' 'subject' 'thanks' 'time'
 'vince' 'vince kaminski']
x_train_vec shape: (4582, 20)
x_test_vec shape : (1146, 20)

Accuracy : 0.9118673647469459
Precision: 0.8203389830508474
Recall   : 0.8344827586206897
F1 Score : 0.8273504273504273

Most Important Spam Words  |  No Spam Words:
subject     |      enron
com     |      vince
time     |      subject
10     |      ect
know     |      2000
group     |      com
thanks     |      kaminski
research     |      thanks
2000     |      research
2001     |      2001
pm     |      know
hou     |      time
cc     |      vince kaminski
ect     |      hou
vince     |      pm


In [4]:
import numpy as np
import pandas as pd
import csv 
from pgmpy.estimators import MaximumLikelihoodEstimator
from pgmpy.models import BayesianNetwork
from pgmpy.inference import VariableElimination

In [9]:
heartDisease = pd.read_csv('./datasets/heart.csv')

In [10]:
print('\n Attributes and datatypes')
print(heartDisease.dtypes)


 Attributes and datatypes
age               int64
sex               int64
cp                int64
trestbps          int64
chol              int64
fbs               int64
restecg           int64
thalach           int64
exang             int64
oldpeak         float64
slope             int64
ca               object
thal             object
heartdisease      int64
dtype: object


In [12]:
print(heartDisease[['age','sex','exang','cp','restecg','chol']])

     age  sex  exang  cp  restecg  chol
0     63    1      0   1        2   233
1     67    1      1   4        2   286
2     67    1      1   4        2   229
3     37    1      0   3        0   250
4     41    0      0   2        2   204
..   ...  ...    ...  ..      ...   ...
298   45    1      0   1        0   264
299   68    1      0   4        0   193
300   57    1      1   4        0   131
301   57    0      0   2        2   236
302   38    1      0   3        0   175

[303 rows x 6 columns]


In [13]:
heartDisease = heartDisease.replace('?',np.nan)
print('Sample instances from the dataset are given below')
print(heartDisease.head())

Sample instances from the dataset are given below
   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

  ca thal  heartdisease  
0  0    6             0  
1  3    3             2  
2  2    7             1  
3  0    3             0  
4  0    3             0  


In [18]:
from sklearn.model_selection import train_test_split
from pgmpy.models import DiscreteBayesianNetwork
#Creat Model- Bayesian Network 
train_df, test_df = train_test_split(heartDisease, test_size=0.2, random_state=42, stratify=heartDisease['heartdisease'])
model = DiscreteBayesianNetwork([('age','heartdisease'),('sex','heartdisease'),(
'exang','heartdisease'),('cp','heartdisease'),('restecg','heartdisease'),('chol','heartdisease')])

In [ ]:
# other estimators are BayesianEstimator, HillClimbSearch
print('\n Learning CPD using Maximum likelihood estimators')
model.fit(heartDisease,estimator=MaximumLikelihoodEstimator)

INFO:pgmpy: Datatype (N=numerical, C=Categorical Unordered, O=Categorical Ordered) inferred from data: 
 {'age': 'N', 'sex': 'N', 'cp': 'N', 'trestbps': 'N', 'chol': 'N', 'fbs': 'N', 'restecg': 'N', 'thalach': 'N', 'exang': 'N', 'oldpeak': 'N', 'slope': 'N', 'ca': 'C', 'thal': 'C', 'heartdisease': 'N'}



 Learning CPD using Maximum likelihood estimators


In [20]:
# -----------------------------
# Inference engine. Other Inference Engines are BeliefPropagation, GibbsSampling
# -----------------------------
infer = VariableElimination(model)

In [25]:
example_patient = {'restecg':1}

result = infer.query(variables=['heartdisease'], evidence=example_patient)
print("\nDiagnosis Probability for example patient:")
print(result)


Diagnosis Probability for example patient:
+-----------------+---------------------+
| heartdisease    |   phi(heartdisease) |
+=================+=====================+
| heartdisease(0) |              0.2000 |
+-----------------+---------------------+
| heartdisease(1) |              0.2000 |
+-----------------+---------------------+
| heartdisease(2) |              0.2000 |
+-----------------+---------------------+
| heartdisease(3) |              0.2000 |
+-----------------+---------------------+
| heartdisease(4) |              0.2001 |
+-----------------+---------------------+


In [27]:
# -----------------------------
# Predict on test set (basic evaluation)
# We'll predict target by taking whichever probability is higher
# -----------------------------
y_true = test_df['heartdisease'].tolist()
y_pred = []

for i in range(len(test_df)):
    row = test_df.iloc[i]
    evidence = {
        'age': int(row['age']),
        'sex': int(row['sex']),
        'restecg': int(row['restecg']),
        'chol': int(row['chol']),
        'exang':int(row['exang']),
        'cp':int(row['cp'])
    }

    q = infer.query(variables=['heartdisease'], evidence=evidence)
    # q.values[0] = P(target=0), q.values[1] = P(target=1)
    pred_class = 1 if q.values[1] > q.values[0] else 0
    y_pred.append(pred_class)

In [35]:
from sklearn.metrics import accuracy_score, precision_score, recall_score
acc = accuracy_score(y_true, y_pred)
prec = precision_score(y_true, y_pred,average='weighted')
rec = recall_score(y_true, y_pred, average='weighted')

print("\n=== Evaluation on Test Data ===")
print("Accuracy :", acc)
print("Precision:", prec)
print("Recall   :", rec)




=== Evaluation on Test Data ===
Accuracy : 0.7213114754098361
Precision: 0.5373770491803279
Recall   : 0.7213114754098361


e:\mtech machine learning\Lab Programs\Sample\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
